openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description:
    This is a description

servers:
  - url: https://localhost:8080/
    description: This is where my api is

tags:
  - name: "Books"
  - name: "Users"

paths:
  /books/{bookId}:
    parameters:
      - name: bookId
        description: book id
        schema:
          type: string
        in: path
        required: true
    get:
      summary: Get a book by id
      operationId: getBookById
      responses:
        "200":
          description: This means it's okay
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /books:

    post:
      summary: Creates a book
      operationId: createBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        "201":
          description: CREATED
    get:
      summary: This gets all books
      description: This is a description
      tags:
        - "Books"
      operationId: getAllBooksInLibrary
      responses:
        "200":
          description: This means it's okay
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH

components:
  schemas:

    Book:
      description: This is the book object
      type: object
      required:
        - name
      properties:
        name:
          description: The name of the book
          type: string
        author:
          description: The name of the author
          type: string